src/Ben/GalleryBundle/Entity/Media.php
<?php

namespace Ben\GalleryBundle\Entity;


use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Media
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Ben\GalleryBundle\Entity\MediaRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Media
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="extension", type="string", length=255)
     */
    private $extension;

    /**
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    /**
     * @Assert\Image()
     * @var UploadedFile file
     */
    private $file;

    /**
     * @ORM\ManyToMany(targetEntity="Ben\GalleryBundle\Entity\Category", cascade={"persist"})
     */
    private $categories;

    public function __construct(){
        $this->categories = new ArrayCollection();
    }


    private $tempFilename;

    public function getFile()
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file)
    {

        $this->file = $file;

        //verif si déjà un fichier pour cette entité
        if(null !== $this->extension){
            $this->tempFilename = $this->extension;

            $this->extension = null;
            $this->alt = null;
        }

    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preLoad(){
        if(null === $this->file){
            return;
        }

        //récupération de l'extension
        $this->extension = $this->file->guessExtension();

        //récupération de l'alt
        $this->alt = $this->file->getClientOriginalName();

    }



    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload(){
        if(null === $this->file){
            return;
        }

        //si ancien fichier on le supprime
        if(null !== $this->tempFilename){
            $oldFile = $this->getUploadRootDir().'/' .$this->id .'.'. $this->tempFilename;
            if (file_exists($oldFile)){
                unlink($oldFile);
            }
        }

        //déplacement du fichier
        $this->file->move(
            $this->getUploadRootDir(),
            $this->id .'.'. $this->extension
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload(){
        //sauvegarde temporaire du nom du fichier
        $this->tempFilename = $this->getUploadRootDir() .'/'. $this->id .'.'. $this->extension;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload(){
        if(file_exists($this->tempFilename)){
            unlink($this->tempFilename);
        }
    }



    public function getUploadDir(){
        //chemin relatif par rapport au dossier web
        return 'uploads/media';
    }

    public function getUploadRootDir(){
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath(){
        return $this->getUploadRootDir().'/'.$this->getId().'.'.$this->getextension();
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set extension
     *
     * @param string $extension
     *
     * @return Media
     */
    public function setextension($extension)
    {
        $this->extension = $extension;

        return $this;
    }

    /**
     * Get extension
     *
     * @return string
     */
    public function getextension()
    {
        return $this->extension;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Media
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }




    public function addCategories(Category $category){
        $this->categories[] = $category;
        return $this;
    }

    public function removedCategory(Category $category){
        $this->categories->removeElement($category);
    }



    public function getCategories()
    {
        return $this->categories;
    }



    /**
     * Add category
     *
     * @param \Ben\GalleryBundle\Entity\Category $category
     *
     * @return Media
     */
    public function addCategory(\Ben\GalleryBundle\Entity\Category $category)
    {
        $this->categories[] = $category;

        return $this;
    }

    /**
     * Remove category
     *
     * @param \Ben\GalleryBundle\Entity\Category $category
     */
    public function removeCategory(\Ben\GalleryBundle\Entity\Category $category)
    {
        $this->categories->removeElement($category);
    }
}

src/Ben/GalleryBundle/Controller/GalleryController.php
<?php

namespace Ben\GalleryBundle\Controller;

use Ben\GalleryBundle\Entity\Media;
use Ben\GalleryBundle\Form\MediaType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class GalleryController extends Controller
{
    public function indexAction(Request $request)
    {
        $media = new Media();

        $form = $this->createForm(new MediaType(),$media);

        if($form->handleRequest($request)->isValid()){

            $em = $this->getDoctrine()->getManager();
            $em->persist($media);
            $em->flush();

            return $this->redirectToRoute('gallery_home');
            }

        $category = $this->getDoctrine()->getRepository('BenGalleryBundle:Category');
        $categories = $category->findAll();

        $med = $this->getDoctrine()->getRepository('BenGalleryBundle:Media');
        $pictures = $med->findMediasByCategory(1);




        return $this->render('BenGalleryBundle:Gallery:index.html.twig',array(
            'form' => $form->createView(),
            'media' => $media,
            'categories' => $categories,
            'pictures' => $pictures

            ));
    }


    public function editAction($id,Request $request){
        $em = $this->getDoctrine()->getManager();

        //récupération de la catégorie

        $category = $em->getRepository('BenGalleryBundle:Category')->find($id);

        if (null === $category){
            throw new NotFoundHttpException("L'annonce d'id " .id." n'existe pas");
        }

        //récupération de tous les médias
        $listMedias = $em->getRepository('BenGalleryBundle:Media')->findAll();



        $em->flush();

       return $this->redirect('gallery_home');
    }



}

src/Ben/GalleryBundle/Resources/views/Gallery/index.html.twig
{% extends '::base.html.twig' %}


    {% block stylesheets %}
        {{ parent() }}

        {% stylesheets
        'jqcoolgallery/css/*'

        filter='cssrewrite' output='css/compiled/app2.css' %}
        <link rel="stylesheet" href="{{ asset_url }}"/>
        {% endstylesheets %}

    {% endblock %}


{% block content %}

    <h1>C'est la galerie de photos !!!</h1>
    {{ form(form) }}


    <h2>Les photos</h2>

    {{ dump(pictures)}}


    <div id="gallery" class="demo">
        <ul class="jqcg-gallery" style="opacity:0;">
{% for category in categories %}



            <li data-title="{{ category.name }}" data-desc="Caption for Gallery {{ category.name }}">
                <img src="#" data-desc="" alt="{{ category.name }}"/>

                <ul class="jqcg-viewer-slides">
    {% for picture in pictures %}
                    <li>
                        <img src="{{ asset(media.uploadDir ~ '/' ~ picture.id ~ '.' ~ picture.extension) }}" alt="{{ picture.alt }}"/>

                        <div class="caption">This is the description for <strong>{{ picture.alt }} 1</strong>.</div>
                    </li>
    {% endfor %}
                </ul>

            </li>

{% endfor %}
        </ul>
    </div>




{% endblock %}






            {% block javascripts %}
                {{ parent() }}
                {% javascripts
                'jqcoolgallery/js/*'

                output='js/compiled/app.js' %}
                <script src="{{ asset_url }}"></script>
                <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
                <script src="{{ path('fos_js_routing_js', {'callback': 'fos.Router.setData'}) }}"></script>


                {% endjavascripts %}


            {% endblock %}